//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PamSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class automationScript
    {
        public int automationScriptId { get; set; }
        public string scriptName { get; set; }
        public int serverOsId { get; set; }
        public string scriptText { get; set; }
        public int serverAccessLevelId { get; set; }
        public System.DateTime lastUpdate { get; set; }
    
        public virtual serverAccessLevel serverAccessLevel { get; set; }
        public virtual serverO serverO { get; set; }
    }
}
