//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PamSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class protectedAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public protectedAccount()
        {
            this.desktopLogs = new HashSet<desktopLog>();
            this.desktopLogs1 = new HashSet<desktopLog>();
            this.sshLogs = new HashSet<sshLog>();
        }
    
        public int protectedAccountId { get; set; }
        public string accountName { get; set; }
        public int serverId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> accountGroupId { get; set; }
        public string note { get; set; }
    
        public virtual accountGroup accountGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<desktopLog> desktopLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<desktopLog> desktopLogs1 { get; set; }
        public virtual server server { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sshLog> sshLogs { get; set; }
    }
}
