//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PamSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class serverAccessLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public serverAccessLevel()
        {
            this.automationScripts = new HashSet<automationScript>();
        }
    
        public int serverAccessId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> departmentId { get; set; }
        public int serverId { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> finishTime { get; set; }
        public Nullable<int> standardAccountId { get; set; }
        public bool allowed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<automationScript> automationScripts { get; set; }
        public virtual department department { get; set; }
        public virtual server server { get; set; }
        public virtual standardAccount standardAccount { get; set; }
        public virtual user user { get; set; }
    }
}
