//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PamSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class standardAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public standardAccount()
        {
            this.accessLogs = new HashSet<accessLog>();
            this.serverAccessLevels = new HashSet<serverAccessLevel>();
        }
    
        public int standardAccountId { get; set; }
        public string accountName { get; set; }
        public string accountAddress { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> accountGroupId { get; set; }
        public string note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accessLog> accessLogs { get; set; }
        public virtual accountGroup accountGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<serverAccessLevel> serverAccessLevels { get; set; }
    }
}
